// Generated by CoffeeScript 1.9.3
var TimeLine, addHover, bigPoint, canvasHeight, canvasWidth, dayFinish, dayStart, dayTime, drawBigPoints, getToday, getUseParams, height, hour, hourText, hoursToMs, line, lineText, markLine, now, now1, now2, now3, offset, room, room2, room3, room4, s, timeLine, ts;

s = Snap('.svg').attr({
  viewBox: '0 0 520 100'
});

canvasWidth = 500;

canvasHeight = 100;

height = 2;

dayStart = 8;

dayFinish = 20;

dayTime = dayFinish - dayStart;

getToday = function() {
  var date;
  date = new Date();
  date.setHours(8);
  return date.setMinutes(0);
};

drawBigPoints = function() {
  var h, i, j, period, ref, results, startPoint;
  period = canvasWidth / dayTime;
  startPoint = 10;
  results = [];
  for (i = j = 0, ref = dayTime; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
    h = hour.clone().appendTo(s);
    h.transform('t' + startPoint);
    h.select('.hourText').node.innerHTML = '00';
    addHover(h);
    results.push(startPoint += period);
  }
  return results;
};

bigPoint = s.circle(0, 5, 1).attr({
  fill: '#999'
}).addClass('hourPoint');

hourText = s.text(0, 3, '').attr({
  fontSize: '4px',
  fill: '#999',
  'font-weight': '100'
}).addClass('hourText');

markLine = s.line(0, 5, 0, 5).attr({
  stroke: '#999',
  'stroke-width': .5
}).addClass('markLine');

hour = s.g(bigPoint, hourText, markLine);

addHover = function(e) {
  e.mouseover(function() {
    this.select('.hourPoint').animate({
      r: 1.5
    }, 200);
    return this.select('.markLine').animate({
      y2: canvasHeight
    }, 200);
  });
  return e.mouseout(function() {
    this.select('.hourPoint').animate({
      r: 1
    }, 200);
    return this.select('.markLine').animate({
      y2: 5
    }, 200);
  });
};

hour.toDefs();

drawBigPoints();

lineText = s.text(1, 15, 'Room1').attr({
  fontSize: '8px',
  fill: '#26A69A',
  'font-weight': 'bold',
  opacity: 0
}).addClass('text');

line = s.rect(0, 20, 0, height).attr({
  fill: '#80CBC4'
}).addClass('line');

timeLine = s.g(lineText, line);

timeLine.toDefs();

ts = s.rect(200, 20, 0, height).attr({
  fill: '#26A69A',
  opacity: 0
}).addClass('inUse');

ts.toDefs();

hoursToMs = function(h) {
  return h * 3600000;
};

now = new Date().getTime();

now1 = now + hoursToMs(.5);

now2 = now + hoursToMs(2);

now3 = now + hoursToMs(2.5);

getUseParams = function(t1, t2) {
  var startLength, startPoint, startTime, useTime, useWidth;
  startTime = t1 - getToday();
  startLength = (startTime / hoursToMs(dayTime)) * 100;
  useTime = (t2 - t1) / (hoursToMs(dayTime)) * 100;
  startPoint = canvasWidth / 100 * startLength;
  useWidth = canvasWidth / 100 * useTime;
  return {
    x: startPoint,
    width: useWidth
  };
};

offset = {
  height: 0,
  get: function() {
    return this.height++ * 20;
  }
};

TimeLine = (function() {
  function TimeLine(params) {
    this.roomName = params.roomName;
    this.times = params.times;
    this.init();
  }

  TimeLine.prototype.addLine = function() {
    return this.timeLine = timeLine.clone().appendTo(s);
  };

  TimeLine.prototype.addRoomName = function() {
    return this.timeLine.select('.text').node.innerHTML = this.roomName;
  };

  TimeLine.prototype.addUses = function() {
    var t;
    t = this.timeLine;
    return this.times.forEach(function(e, i, arr) {
      t.append(ts.clone().attr(getUseParams(arr[i], arr[i + 1])));
      arr.splice(0, 1);
    });
  };

  TimeLine.prototype.setAnimation = function() {
    var t;
    t = this.timeLine;
    return t.select('.line').animate({
      width: canvasWidth
    }, 1000, function() {
      t.select('.text').animate({
        opacity: 1
      }, 500);
      return t.selectAll('.inUse').animate({
        opacity: 1
      }, 500);
    });
  };

  TimeLine.prototype.init = function() {
    this.addLine();
    this.addRoomName();
    this.addUses();
    this.timeLine.transform('t10,' + offset.get());
    return this.setAnimation();
  };

  return TimeLine;

})();

room = new TimeLine({
  roomName: 'Red Room',
  times: [now, now1, now2, now3]
});

room2 = new TimeLine({
  roomName: 'Blue Room',
  times: [now, now1, now2, now3]
});

room3 = new TimeLine({
  roomName: 'Grey Room',
  times: [now, now1, now2, now3]
});

room4 = new TimeLine({
  roomName: 'Grey hjk Room',
  times: []
});

//# sourceMappingURL=animation.js.map
